/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3DhtAhVG6xq
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";

import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardFooter,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { JSX, SVGProps } from "react";

const getIssues = async () => {
  const response = await fetch(`${process.env.SERVER_URL}/api/github/issues`, {
    next: { revalidate: 60 },
  });
  if (response.ok) {
    console.log(response);
    return response.json();
  }
};

const getCommits = async () => {
  const response = await fetch(`${process.env.SERVER_URL}/api/github/commits`, {
    next: { revalidate: 60 },
  });
  if (response.ok) {
    console.log(response);
    return response.json();
  }
};

export async function Tracker() {
  const issues = await getIssues();
  const commits = await getCommits();
  console.log(commits);
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <GithubIcon className="w-6 h-6" />
          <h1 className="text-xl font-semibold">Tracker</h1>
        </div>
      </header>
      <main className="flex-1 grid grid-cols-1 md:grid-cols-2 gap-8 p-8">
        <section>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-xl font-semibold">Open Issues</h2>
            <Link href={"https://github.com/subinoybiswas/AmiMoji/issues/new"}>
              <Button>
                <PlusIcon className="w-4 h-4 mr-2" />
                Create Issue
              </Button>
            </Link>
          </div>
          <div className="grid gap-4">
            {issues.issues.map((issue: any) => (
              <Link href={issue.html_url} key={issue.url}>
                <Card
                  key={issue.url}
                  className="hover:border-2 hover:border-blue-800 cursor-pointer"
                >
                  <CardHeader>
                    <CardTitle>{issue.title}</CardTitle>
                  </CardHeader>
                  <CardFooter>
                    <Badge variant="secondary" className="text-xs">
                      {issue.state}
                    </Badge>
                  </CardFooter>
                </Card>
              </Link>
            ))}
          </div>
        </section>
        <section>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-xl font-semibold">Recent Commits</h2>
            <Link
              href={"https://github.com/subinoybiswas/AmiMoji/commits/main/"}
            >
              <Button>
                <GitCommitVerticalIcon className="w-4 h-4 mr-2" />
                View History
              </Button>
            </Link>
          </div>
          <div className="grid gap-4">
            {commits.commits.map((commit: any) => (
              <Link href={commit.html_url} key={commit.sha}>
                <Card className="hover:border-2 hover:border-blue-800 cursor-pointer">
                  <CardHeader>
                    <CardTitle>{commit.commit.message}</CardTitle>
                  </CardHeader>
                  <CardFooter className="flex items-center justify-between">
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <GithubIcon className="w-4 h-4" />
                      <span>{commit.commit.author.name}</span>
                    </div>
                    <div className="text-sm text-muted-foreground">
                      {commit.commit.author.date}
                    </div>
                  </CardFooter>
                </Card>
              </Link>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}

function GitCommitVerticalIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3v6" />
      <circle cx="12" cy="12" r="3" />
      <path d="M12 15v6" />
    </svg>
  );
}

function GithubIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

function PlusIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}
